name: "Blog"
description: ""
meta_description: "My blog & thoughts"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: "/blog"
production_url : http://piyushkhemka.github.io.com/blog
BASE_PATH : "https://piyushkhemka.me/blog"
domain_name: "https://piyushkhemka.me/"
google_analytics: "UA-79238615-2"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://piyushkhemka.me/blog/"
author: "Piyush Khemka"

# Disqus config
disqus-shortname: "piyushkhemka"
disqus: "piyushkhemka"
sass:
    sass_dir: "_sass"
    

# Prevents the url to be generated like this
# http://domaine.tld/category/2014/11/22/post.html.
# Instead generates http://domaine.tld/title.html
permalink: /:title.html

